spring.application.name=challenge-forohub
spring.datasource.url=jdbc:mysql://localhost/foro_hub
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root1984

spring.jpa.show-sql=true
spring.jpa.propiertes.hibernate.format_sql=true

